_BASE_: [
  '../datasets/mot.yml',
  '../runtime.yml',
  '_base_/optimizer_30e.yml',
  '_base_/fairmot_resnet50.yml',
  '_base_/fairmot_reader_1088x608.yml',
]

weights: output/fairmot_renet50_30e_1088x608/model_final
