_BASE_: [
  '../datasets/mot_n.yml',
  '../runtime.yml',
  '_base_/optimizer_30e.yml',
  '_base_/fairmot_dla34.yml',
  '_base_/fairmot_reader_864x480_n.yml',
]

weights: output/fairmot_dla34_30e_864x480/model_final
